version: "3.8"

services:
  yuviron-redis:
    image: redis:alpine
    container_name: yuviron_redis
    restart: always
    ports:
      - "6379:6379"

  yuviron-mysql:
    image: mysql:8.0
    container_name: yuviron_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: yuviron_db
      MYSQL_USER: yuviron_user
      MYSQL_PASSWORD: supersecret123
    ports:
      - "3306:3306"
    volumes:
      - yuviron_mysql_data:/var/lib/mysql

  yuviron-clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: yuviron_clickhouse
    restart: always
    environment:
      CLICKHOUSE_USER: yuviron_user
      CLICKHOUSE_PASSWORD: supersecret123
      CLICKHOUSE_DB: yuviron_analytics
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123" 
      - "9000:9000" 
    volumes:
      - yuviron_clickhouse_data:/var/lib/clickhouse

  yuviron-seq:
    image: datalust/seq:latest
    container_name: yuviron_seq
    restart: always
    user: "root"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "8081:80"
      - "5341:5341"
    volumes:
      - yuviron_seq_data_new:/data

  yuviron-aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    container_name: yuviron_dashboard
    restart: always
    environment:
      - ASPIRE_ALLOW_UNSECURED_TRANSPORT=true
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
      - DOTNET_DASHBOARD_OTLP_ENDPOINT_URL=http://0.0.0.0:4317
    ports:
      - "18888:18888"
      - "4317:4317"
  
  yuviron-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: yuviron_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  yuviron_mysql_data:
  yuviron_seq_data_new:
  yuviron_clickhouse_data: