name: Deploy backend

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: [self-hosted, yuviron]

    steps:
      - name: Update backend source
        run: |
          set -e
          cd /opt/yuviron/src/yuviron-backend
          git fetch origin dev
          git reset --hard origin/dev
          git clean -fd

      - name: Generate Secrets Config
        run: |
          set -e
          if [ "${{ github.ref_name }}" = "dev" ]; then
            ENV_FILE="Development"
          else
            ENV_FILE="Production"
          fi
          
          CONFIG_PATH="/opt/yuviron-server/src/yuviron-backend/src/Yuviron.Api/appsettings.${ENV_FILE}.json"
          
          cat <<EOF > $CONFIG_PATH
          {
            "JwtSettings": {
              "Secret": "${{ secrets.JWT_SECRET }}",
              "Issuer": "YuvironApi",
              "Audience": "YuvironClient",
              "ExpiryMinutes": 60
            },
            "Email": {
              "Host": "smtp.gmail.com",
              "Port": 587,
              "Username": "${{ secrets.EMAIL_USERNAME }}",
              "Password": "${{ secrets.EMAIL_PASSWORD }}"
            },
            "SeedUsers": {
              "Admin": { "Email": "${{ secrets.SEED_ADMIN_EMAIL }}", "Password": "${{ secrets.SEED_ADMIN_PASSWORD }}" },
              "Manager": { "Email": "${{ secrets.SEED_MANAGER_EMAIL }}", "Password": "${{ secrets.SEED_MANAGER_PASSWORD }}" },
              "User": { "Email": "${{ secrets.SEED_USER_EMAIL }}", "Password": "${{ secrets.SEED_USER_PASSWORD }}" },
              "Premium": { "Email": "${{ secrets.SEED_PREMIUM_EMAIL }}", "Password": "${{ secrets.SEED_PREMIUM_PASSWORD }}" }
            }
          }
          EOF
          echo "✅ Configuration generated for environment: ${ENV_FILE}"

      - name: Apply EF Core migrations
        run: |
          set -e
          cd /opt/yuviron/infra
          docker compose -f compose.dev.yml run --rm yuviron-dev-migrator

      - name: Rebuild and restart services
        run: |
          set -e
          cd /opt/yuviron/infra
          docker compose -f compose.dev.yml up -d --build --force-recreate yuviron-dev-backend yuviron-dev-frontend yuviron-dev-nginx